#!/usr/bin/env python3
"""Regenerate paper/erdos307-short.tex, the abridged submission version, from the full note.

The full note is the record of the work; the abridged version is what a referee reads. This script
derives the second from the first so the two cannot drift, which is the Rule 9 requirement: anything
in the paper is regenerated by a committed script rather than hand-edited twice.

WHAT IS DROPPED, AND WHY IT IS NOT A FREE CHOICE. Selecting whole sections rather than individual
results, the natural core leaves 17 references pointing into what would be dropped, and among them
are thm:lyapfalse, thm:halflyap, thm:noinvariant, prop:untestable and rem:whatisleft, which are the
strongest no-gos in the note. sec:exclosure therefore stays. What goes is sec:ladderplus,
sec:sqsieve and the square-sieve appendix.

That still leaves references crossing the boundary, including prop:noplace and prop:nogain, which
are the formalised atoms A5 and A8. Rather than break them or restate them, each is rewritten as a
citation carrying the full version's own number, e.g. "Proposition 13.1(2) of the full version",
with part-references preserved. The numbers are read from erdos307.aux, so the full note must be
built first.

The abstract is also trimmed: it devotes six lines to the square sieve, its conditional rate and the
three obstructions to the exponent N^{1/2}, none of which survives into this version. An abstract
advertising absent content is exactly what the label discipline exists to prevent.

Usage:  cd paper && pdflatex erdos307.tex && python3 ../code/build_short.py && pdflatex erdos307-short.tex
"""
import json
import re
import sys
from pathlib import Path

PAPER = Path("erdos307.tex")
AUX = Path("erdos307.aux")
OUT = Path("erdos307-short.tex")

KEEP = {
    "sec:intro", "sec:rigidity", "sec:bridge", "sec:barrier", "sec:anatomy", "sec:ff",
    "sec:frame", "sec:breeder", "sec:computations", "sec:lean", "sec:status", "sec:prior",
    "sec:exclosure",
}
ENV = {"cor": "Corollary", "prop": "Proposition", "lem": "Lemma", "thm": "Theorem", "rem": "Remark"}


def main() -> int:
    if not PAPER.exists() or not AUX.exists():
        print("run from paper/, after building erdos307.tex at least once", file=sys.stderr)
        return 1

    lines = PAPER.read_text().split("\n")
    heads = [(i, l) for i, l in enumerate(lines)
             if l.startswith("\\section{") or l.startswith("\\appendix")]
    bounds = []
    for k, (i, l) in enumerate(heads):
        end = heads[k + 1][0] if k + 1 < len(heads) else len(lines)
        m = re.search(r"\\label\{(sec:[a-z]+|app:[a-z]+)\}", l)
        bounds.append((m.group(1) if m else "\\appendix", i, end))

    bib_i = next(i for i, l in enumerate(lines) if l.startswith("\\begin{thebibliography}"))
    pre = lines[: bounds[0][1]]
    bib = lines[bib_i:]

    keep, drop = [], []
    for name, i, e in bounds:
        (keep if name in KEEP else drop).extend(lines[i: min(e, bib_i)])

    kept, dropped = "\n".join(keep), "\n".join(drop)
    crossing = sorted(set(re.findall(r"\\label\{([^}]+)\}", dropped))
                      & set(re.findall(r"\\(?:ref|eqref)\{([^}]+)\}", kept)))

    numbers = {m.group(1): m.group(2)
               for m in re.finditer(r"\\newlabel\{([^}]+)\}\{\{([^}]*)\}\{(\d+)\}", AUX.read_text())}

    body = kept
    unnumbered = []
    for lab in crossing:
        n = numbers.get(lab)
        if n is None:
            unnumbered.append(lab)
            continue
        kind = ENV.get(lab.split(":")[0], "Result")
        pat = (r"(?:[A-Z][a-z]+~)?\\ref\{%s\}(\\textup\{\([^)]*\)\}|\([ivxIVX0-9]+\))?"
               % re.escape(lab))
        body = re.sub(pat, lambda m: f"{kind}~{n}{m.group(1) or ''} of the full version", body)
    if unnumbered:
        print(f"ERROR: no number in .aux for {unnumbered}; rebuild the full note", file=sys.stderr)
        return 1

    preamble = "\n".join(pre)
    a, b = ("The minus layer $m'-2m=d^2$ is the set on which the arithmetic derivative takes",
            "large-sieve reformulation is circular at its principal term.")
    if a in preamble and b in preamble:
        i, j = preamble.index(a), preamble.index(b) + len(b)
        preamble = preamble[:i] + (
            "Both Pythagorean layers have density zero on the squarefree stratum by a square--sieve "
            "argument; that argument, its conditional rate and the three obstructions to the sharp "
            "exponent $N^{1/2}$ are given in the full version and are not reproduced here."
        ) + preamble[j:]

    note = (r"""
\begin{center}\small\textit{Abridged version.} This note omits the deviation ladder, the plus--layer
analysis and the square sieve, together with their proofs, and cites their statements by the
numbering of the full version, which is archived with the Lean development and the computational
scripts. Nothing proved here depends on a proof appearing only there.\end{center}
""")
    short = (preamble + "\n" + note + "\n" + body + "\n" + "\n".join(bib))
    short = short.replace(r"\title{", r"\title{Abridged: ", 1)
    OUT.write_text(short)

    print(f"wrote {OUT}: {len(short.splitlines())} lines "
          f"(full note {len(lines)}), {len(crossing)} references rewritten as citations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
