\\ immune_certify.gp -- INDEPENDENTLY CHECKABLE ECPP certificates for the immune families.
\\
\\ immune_prove.gp settles primality with APR-CL, but isprime() returns a VERDICT, not a
\\ certificate: nobody can check it without re-running the same program. ECPP (Atkin-Morain)
\\ emits a certificate that a third party verifies without trusting the prover. primecert()
\\ produces it and primecertisvalid() checks it; the exported Primo-format files can also be
\\ checked by tools with no PARI code in common.
\\
\\ Run:  gp -q -f immune_certify.gp
default(parisize, 2000000000);
P    = primes([2,800]);
T58  = sum(i=1, 58, 1/P[i]);
forc = select(x -> x <= 167, P);
pool = select(x -> x > 167 && T58 + 1/x > 2, P);
np = #pool; kk = 59 - #forc;
thr  = 2 - sum(i=1, #forc, 1/forc[i]);
pf   = vector(np, i, 1/pool[i]);
cum  = vector(np+1); cum[1] = 0;
for(i=1, np, cum[i+1] = cum[i] + pf[i]);
bases = List();
dfs(i, need, cur, chosen) = {
  if(need == 0, if(cur > thr, listput(bases, chosen)); return());
  if(i + need > np + 1, return());
  if(cur + (cum[min(i+need, np+1)] - cum[i]) <= thr, return());
  dfs(i+1, need-1, cur + pf[i], concat(chosen, [i]));
  dfs(i+1, need,   cur,          chosen);
};
dfs(1, kk, 0, []);
imm = List();
{
for(j=1, #bases,
  S = concat(forc, vector(#bases[j], t, pool[bases[j][t]]));
  D = prod(t=1, #S, S[t]);
  N = sum(t=1, #S, D \ S[t]);
  A = N + 2*D; B = N - 2*D;
  if(ispseudoprime(A) && ispseudoprime(B) && kronecker(D, A) == 1, listput(imm, [A, B]));
);
}
printf("immune families: %d (expected 34)\n\n", #imm);

nv = 0; nbad = 0; tot = 0;
outf = "../certs/immune_ecpp.txt";
write(outf, "ECPP certificates (Atkin-Morain) for the 34 level-60 immune families of rem:campaign.");
write(outf, "Each A_S and B_S is proven prime. Verify with PARI:  primecertisvalid(cert)");
write(outf, "Generated by code/immune_certify.gp, PARI/GP " Str(version()) ".");
{
for(j=1, #imm,
  for(k=1, 2,
    n = imm[j][k];
    t0 = getabstime();
    c = primecert(n);
    v = primecertisvalid(c);
    t1 = getabstime();
    tot += (t1 - t0);
    if(v, nv++, nbad++; printf("  *** CERTIFICATE INVALID: family %d %s\n", j, if(k==1,"A","B")));
    write(outf, "");
    write(outf, Str("### family ") Str(j) Str(if(k==1, " A_S", " B_S")) Str("  digits=") Str(#digits(n)) Str("  valid=") Str(v));
    write(outf, n);
    write(outf, primecertexport(c));
  );
  if(j % 5 == 0, printf("  ... %d/%d families certified (%.0fs)\n", j, #imm, tot/1000.0));
);
}
printf("\ncertificates VERIFIED: %d   invalid: %d   total time %.1fs\n", nv, nbad, tot/1000.0);
if(nbad == 0 && nv == 2*#imm,
  printf("=> all %d numbers carry an independently checkable ECPP certificate.\n", nv));
quit;
