import Erdos307.Pratt

/-!
# Pratt certificates for the primes of the `N_10` inheritance result

`P60` is the sixty-digit prime factor of `N_10 ^ 2 + 1`, and `N9 + 1` is the largest prime factor of
`N_10`. Each is certified by a Pratt tree whose leaves lie below `10^9` and are decided by
`norm_num`; the internal nodes are listed bottom-up, so each cites only earlier ones. The data are
generated by `code/pratt_n10.gp`.

Paper: Proposition `prop:ppninherit`.
-/

namespace Erdos307

/-- Pratt node: witness 7, `p - 1 = 2 * 3 * 5 * 7 * 19919 * 2375059`. -/
theorem prime_c1 : Nat.Prime 9934848046411 := by
  refine pratt 9934848046411 7 [2, 3, 5, 7, 19919, 2375059] ?_ (by norm_num)
    (by simp only [Nat.reduceSub]; reduce_mod_char) ?_
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl | rfl | rfl <;> first | norm_num
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl | rfl | rfl <;> (simp only [Nat.reduceSub, Nat.reduceDiv]; reduce_mod_char; decide)

/-- Pratt node: witness 2, `p - 1 = 2 * 2 * 3 * 3 * 6151 * 895313`. -/
theorem prime_c2 : Nat.Prime 198254529469 := by
  refine pratt 198254529469 2 [2, 2, 3, 3, 6151, 895313] ?_ (by norm_num)
    (by simp only [Nat.reduceSub]; reduce_mod_char) ?_
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl | rfl | rfl <;> first | norm_num
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl | rfl | rfl <;> (simp only [Nat.reduceSub, Nat.reduceDiv]; reduce_mod_char; decide)

/-- Pratt node: witness 2, `p - 1 = 2 * 29 * 191 * 108887`. -/
theorem prime_c3 : Nat.Prime 1206250187 := by
  refine pratt 1206250187 2 [2, 29, 191, 108887] ?_ (by norm_num)
    (by simp only [Nat.reduceSub]; reduce_mod_char) ?_
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl <;> first | norm_num
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl <;> (simp only [Nat.reduceSub, Nat.reduceDiv]; reduce_mod_char; decide)

/-- Pratt node: witness 2, `p - 1 = 2 * 2 * 258407 * 1206250187`. -/
theorem prime_c4 : Nat.Prime 1246813968288437 := by
  refine pratt 1246813968288437 2 [2, 2, 258407, 1206250187] ?_ (by norm_num)
    (by simp only [Nat.reduceSub]; reduce_mod_char) ?_
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl <;> first | exact prime_c3 | norm_num
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl <;> (simp only [Nat.reduceSub, Nat.reduceDiv]; reduce_mod_char; decide)

/-- Pratt node: witness 6, `p - 1 = 2 * 5 * 41 * 1246813968288437`. -/
theorem prime_c5 : Nat.Prime 511193726998259171 := by
  refine pratt 511193726998259171 6 [2, 5, 41, 1246813968288437] ?_ (by norm_num)
    (by simp only [Nat.reduceSub]; reduce_mod_char) ?_
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl <;> first | exact prime_c4 | norm_num
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl <;> (simp only [Nat.reduceSub, Nat.reduceDiv]; reduce_mod_char; decide)

/-- Pratt node: witness 10, `p - 1 = 2 * 2 * 3 * 3 * 67 * 509 * 511193726998259171`. -/
theorem prime_c6 : Nat.Prime 627596628185578770310069 := by
  refine pratt 627596628185578770310069 10 [2, 2, 3, 3, 67, 509, 511193726998259171] ?_ (by norm_num)
    (by simp only [Nat.reduceSub]; reduce_mod_char) ?_
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> first | exact prime_c5 | norm_num
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> (simp only [Nat.reduceSub, Nat.reduceDiv]; reduce_mod_char; decide)

/-- Pratt node: witness 2, `p - 1 = 2 * 3 * 23 * 198254529469 * 627596628185578770310069`. -/
theorem prime_c7 : Nat.Prime 17170494641982275000057653242253423819 := by
  refine pratt 17170494641982275000057653242253423819 2 [2, 3, 23, 198254529469, 627596628185578770310069] ?_ (by norm_num)
    (by simp only [Nat.reduceSub]; reduce_mod_char) ?_
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl | rfl <;> first | exact prime_c2 | exact prime_c6 | norm_num
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl | rfl <;> (simp only [Nat.reduceSub, Nat.reduceDiv]; reduce_mod_char; decide)

/-- Pratt node: witness 5, `p - 1 = 2 * 1534739 * 9934848046411 * 17170494641982275000057653242253423819`. -/
theorem prime_c8 : Nat.Prime 523610757284722813428780593626623950286030035549220826103 := by
  refine pratt 523610757284722813428780593626623950286030035549220826103 5 [2, 1534739, 9934848046411, 17170494641982275000057653242253423819] ?_ (by norm_num)
    (by simp only [Nat.reduceSub]; reduce_mod_char) ?_
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl <;> first | exact prime_c1 | exact prime_c7 | norm_num
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl <;> (simp only [Nat.reduceSub, Nat.reduceDiv]; reduce_mod_char; decide)

/-- Pratt node: witness 2, `p - 1 = 2 * 2 * 59 * 523610757284722813428780593626623950286030035549220826103`. -/
theorem prime_c9 : Nat.Prime 123572138719194583969192220095883252267503088389616114960309 := by
  refine pratt 123572138719194583969192220095883252267503088389616114960309 2 [2, 2, 59, 523610757284722813428780593626623950286030035549220826103] ?_ (by norm_num)
    (by simp only [Nat.reduceSub]; reduce_mod_char) ?_
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl <;> first | exact prime_c8 | norm_num
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl <;> (simp only [Nat.reduceSub, Nat.reduceDiv]; reduce_mod_char; decide)

/-- Pratt node: witness 3, `p - 1 = 2 * 3 * 11 * 17 * 101 * 157 * 1979 * 10093 * 16879`. -/
theorem prime_c10 : Nat.Prime 5998279018951962403 := by
  refine pratt 5998279018951962403 3 [2, 3, 11, 17, 101, 157, 1979, 10093, 16879] ?_ (by norm_num)
    (by simp only [Nat.reduceSub]; reduce_mod_char) ?_
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> first | norm_num
  · intro q hq
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hq
    rcases hq with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> (simp only [Nat.reduceSub, Nat.reduceDiv]; reduce_mod_char; decide)

end Erdos307
